package display

// DistroLogos contains the authentic, accurate ASCII art distro logos from neofetch/fastfetch.
var DistroLogos = map[string][]string{
	"arch": {
		"                  -`",
		"                 .o+`",
		"                `ooo/",
		"               `+oooo:",
		"              `+oooooo:",
		"              -+oooooo+:",
		"            `/:-:++oooo+:",
		"           `/++++/+++++++:",
		"          `/++++++++++++++:",
		"         `/+++ooooooooooooo/`",
		"        ./ooosssso++osssssso+`",
		"       .oossssso-````/ossssss+`",
		"      -osssssso.      :ssssssso.",
		"     :osssssss/        osssso+++.",
		"    /ossssssss/        +ssssooo/-",
		"  `/ossssso+/:-        -:/+osssso+-",
		" `+sso+:-`                 `.-/+oso:",
		"`++:.                           `-/+/",
		".`                                 `/",
	},
	"manjaro": {
		"██████████████████  ████████",
		"██████████████████  ████████",
		"██████████████████  ████████",
		"██████████████████  ████████",
		"████████            ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
	},
	"ubuntu": {
		"                             ....",
		"              .',:clooo:  .:looooo:.",
		"           .;looooooooc  .oooooooooo'",
		"        .;looooool:,''.  :ooooooooooc",
		"       ;looool;.         'oooooooooo,",
		"      ;clool'             .cooooooc.  ,,",
		"         ...                ......  .:oo,",
		"  .;clol:,.                        .loooo'",
		" :ooooooooo,                        'ooool",
		"'ooooooooooo.                        loooo.",
		"'ooooooooool                         coooo.",
		" ,loooooooc.                        .loooo.",
		"   .,;;;'.                          ;ooooc",
		"       ...                         ,ooool.",
		"    .cooooc.              ..',,'.  .cooo.",
		"      ;ooooo:.           ;oooooooc.  :l.",
		"       .coooooc,..      coooooooooo.",
		"         .:ooooooolc:. .ooooooooooo'",
		"           .':loooooo;  ,oooooooooc",
		"               ..';::c'  .;loooo:'",
	},
	"debian": {
		"        _,met$$$$$gg.",
		"     ,g$$$$$$$$$$$$$$$P.",
		"   ,g$$P\"\"       \"\"\"Y$$\".\"",
		"  ,$$P'              `$$$.",
		"',$$P       ,ggs.     `$$b:",
		"`d$$'     ,$P\"'   .    $$$",
		" $$P      d$'     ,    $$P",
		" $$:      $$.   -    ,d$$'",
		" $$;      Y$b._   _,d$P'",
		" Y$$.    `.`\"Y$$$$P\"'",
		" `$$b      \"-.__",
		"  `Y$$b",
		"   `Y$$.",
		"     `$$b.",
		"       `Y$$b.",
		"         `\"Y$b._",
		"             `\"\"\"\"",
	},
	"fedora": {
		"             .',;::::;,'..",
		"         .';:cccccccccccc:;,.",
		"      .;cccccccccccccccccccccc;.",
		"    .:cccccccccccccccccccccc:.",
		"  .;ccccccccccccc;.:dddl:.;ccccccc;.",
		" .:ccccccccccccc;OWMKOOXMWd;ccccccc:.",
		".:ccccccccccccc;KMMc;cc;xMMc;ccccccc:.",
		",cccccccccccccc;MMM.;cc;;WW:;cccccccc,",
		":cccccccccccccc;MMM.;cccccccccccccccc:",
		":ccccccc;oxOOOo;MMM000k.;cccccccccccc:",
		"cccccc;0MMKxdd:;MMMkddc.;cccccccccccc;",
		"ccccc;XMO';cccc;MMM.;cccccccccccccccc'",
		"ccccc;MMo;ccccc;MMW.;ccccccccccccccc;",
		"ccccc;0MNc.ccc.xMMd;ccccccccccccccc;",
		"cccccc;dNMWXXXWM0:;cccccccccccccc:,",
		"cccccccc;.:odl:.;cccccccccccccc:,.",
		"ccccccccccccccccccccccccccccc:'.",
		":ccccccccccccccccccccccc:;,..",
		" ':cccccccccccccccc::;,,.",
	},
	"macos": {
		"                     ..'",
		"                 ,xNMM.",
		"               .OMMMMo",
		"               lMM\"",
		"     .;loddo:.  .olloddol;.",
		"   cKMMMMMMMMMMNWMMMMMMMMMM0:",
		" .KMMMMMMMMMMMMMMMMMMMMMMMWd.",
		" XMMMMMMMMMMMMMMMMMMMMMMMX.",
		";MMMMMMMMMMMMMMMMMMMMMMMM:",
		":MMMMMMMMMMMMMMMMMMMMMMMM:",
		".MMMMMMMMMMMMMMMMMMMMMMMMX.",
		" kMMMMMMMMMMMMMMMMMMMMMMMMWd.",
		" 'XMMMMMMMMMMMMMMMMMMMMMMMMMMk",
		"  'XMMMMMMMMMMMMMMMMMMMMMMMMK.",
		"    kMMMMMMMMMMMMMMMMMMMMMMd",
		"     ;KMMMMMMMWXXWMMMMMMMk.",
		"       \"cooc*\"    \"*coo'\"",
	},
	"windows": {
		"        ,.=:!!t3Z3z.,",
		"       :tt:::tt333EE3",
		"       Et:::ztt33EEEL @Ee.,      ..,",
		"      ;tt:::tt333EE7 ;EEEEEEttttt33#",
		"     :Et:::zt333EEQ. $EEEEEttttt33QL",
		"     it::::tt333EEF @EEEEEEttttt33F",
		"    ;3=*^```\"*4EEV :EEEEEEttttt33@.",
		"    ,.=::::!t=., ` @EEEEEEtttz33QF",
		"   ;::::::::zt33)   \"4EEEtttji3P*",
		"  :t::::::::tt33.:Z3z..  `` ,..g.",
		"  i::::::::zt33F AEEEtttt::::ztF",
		" ;:::::::::t33V ;EEEttttt::::t3",
		" E::::::::zt33L @EEEtttt::::z3F",
		"{3=*^```\"*4E3) ;EEEtttt:::::tZ`",
		"             ` :EEEEtttt::::z7",
		"                 \"VEzjt:;;z>*`",
	},
	"linux": {
		"        #####",
		"       #######",
		"       ##O#O##",
		"       #######",
		"     ###########",
		"    #############",
		"   ###############",
		"   ################",
		"  #################",
		"#####################",
		"#####################",
		"  #################",
	},
	"alpine": {
		"       .hddddddddddddddddddddddh.",
		"      :dddddddddddddddddddddddddd:",
		"     /dddddddddddddddddddddddddddd/",
		"    +dddddddddddddddddddddddddddddd+",
		"  `sdddddddddddddddddddddddddddddddds`",
		" `ydddddddddddd++hdddddddddddddddddddy`",
		".hddddddddddd+`  `+ddddh:-sdddddddddddh.",
		"hdddddddddd+`      `+y:    .sddddddddddh",
		"ddddddddh+`   `//`   `.`     -sddddddddd",
		"ddddddh+`   `/hddh/`   `:s-    -sddddddd",
		"ddddh+`   `/+/dddddh/`   `+s-    -sddddd",
		"ddd+`   `/o` :dddddddh/`   `oy-    .yddd",
		"hdddyo+ohddyosdddddddddho+oydddy++ohdddh",
		".hddddddddddddddddddddddddddddddddddddh.",
		" `yddddddddddddddddddddddddddddddddddy`",
		"  `sdddddddddddddddddddddddddddddddds`",
		"    +dddddddddddddddddddddddddddddd+",
		"     /dddddddddddddddddddddddddddd/",
		"      :dddddddddddddddddddddddddd:",
		"       .hddddddddddddddddddddddh.",
	},
	"gentoo": {
		"         -/oyddmdhs+:.",
		"     -odNMMMMMMMMNNmhy+-`",
		"   -yNMMMMMMMMMMMNNNmmdhy+-",
		" `omMMMMMMMMMMMMNmdmmmmddhhy/`",
		" omMMMMMMMMMMMNhhyyyohmdddhhhdo`",
		".ydMMMMMMMMMMdhs++so/smdddhhhhdm+`",
		" oyhdmNMMMMMMMNdyooydmddddhhhhyhNd.",
		"  :oyhhdNNMMMMMMMNNNmmdddhhhhhyymMh",
		"    .:+sydNMMMMMNNNmmmdddhhhhhhmMmy",
		"       /mMMMMMMNNNmmmdddhhhhhmMNhs:",
		"    `oNMMMMMMMNNNmmmddddhhdmMNhs+`",
		"  `sNMMMMMMMMNNNmmmdddddmNMmhs/.",
		" /NMMMMMMMMNNNNmmmdddmNMNdso:`",
		"+MMMMMMMNNNNNmmmmdmNMNdso/-",
		"yMMNNNNNNNmmmmmNNMmhs+/-`",
		"/hMMNNNNNNNNMNdhs++/-`",
		"`/ohdmmddhys+++/:.`",
		"  `-//////:--.",
	},
	"redhat": {
		"           .MMM..:MMMMMMM",
		"          MMMMMMMMMMMMMMMMMM",
		"          MMMMMMMMMMMMMMMMMMMM.",
		"         MMMMMMMMMMMMMMMMMMMMMM",
		"        ,MMMMMMMMMMMMMMMMMMMMMM:",
		"        MMMMMMMMMMMMMMMMMMMMMMMM",
		"  .MMMM'  MMMMMMMMMMMMMMMMMMMMMM",
		" MMMMMM    `MMMMMMMMMMMMMMMMMMMM.",
		"MMMMMMMM      MMMMMMMMMMMMMMMMMM .",
		"MMMMMMMMM.       `MMMMMMMMMMMMM' MM.",
		"MMMMMMMMMMM.                     MMMM",
		"`MMMMMMMMMMMMM.                 ,MMMMM.",
		" `MMMMMMMMMMMMMMMMM.          ,MMMMMMMM.",
		"    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
		"      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:",
		"         MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
		"            `MMMMMMMMMMMMMMMMMMMMMMMM:",
		"                ``MMMMMMMMMMMMMMMMM'",
	},
	"opensuse": {
		"           .;ldkO0000Okdl;.",
		"       .;d00xl:^''''''^:ok00d;.",
		"     .d00l'                'o00d.",
		"   .d0Kd'  Okxol:;,.          :O0d",
		"  .OKKKK0kOKKKKKKKKKKOxo:,      lKO.",
		" ,0KKKKKKKKKKKKKKKK0P^,,,^dx:    ;00,",
		".OKKKKKKKKKKKKKKKKk'.oOPPb.'0k.   cKO.",
		":KKKKKKKKKKKKKKKKK: kKx..dd lKd   'OK:",
		"dKKKKKKKKKKKOx0KKKd ^0KKKO' kKKc   dKd",
		"dKKKKKKKKKKKK;.;oOKx,..^..;kKKK0.  dKd",
		":KKKKKKKKKKKK0o;...^cdxxOK0O/^^'  .0K:",
		" kKKKKKKKKKKKKKKK0x;,,......,;od  lKk",
		" '0KKKKKKKKKKKKKKKKKKKKK00KKOo^  c00'",
		"  'kKKKOxddxkOO00000Okxoc;''   .dKk'",
		"    l0Ko.                    .c00l'",
		"     'l0Kk:.              .;xK0l'",
		"        'lkK0xl:;,,,,;:ldO0kl'",
		"            '^:ldxkkkkxdl:^'",
	},
	"mint": {
		"          cMMMMMMMMMMMMMMMMMMMMMMMMMMd",
		"        cMMm:                        :MMd",
		"      cMMm:                            :MMd",
		"     cMMm:  .cMMMMMMMMMMMMMMMMMMMMMMd.  :MMd",
		"    cMMm:  cMMm:cMMMMMMMMMMMMMMMMMMMMMd  :MMd",
		"   cMMm:  cMMm:  :MMMMMMMMMMMMMMMMMMMMMd  :MMd",
		"  cMMm:  cMMm:    :MMMMMMMMMMMMMMMMMMMMMd  :MMd",
		" cMMm:  cMMm:      .cMMMMMMMMMMMMMMMMMMMMd  :MMd",
		" cMMm:  cMMm:        cMMMMMMMMMMMMMMd.       :MMd",
		" cMMm:  cMMm:        cMMm:cMMMMMMMMMd        :MMd",
		" cMMm:  cMMm:        cMMm:  :MMMMMMMd        :MMd",
		" cMMm:  cMMm:        cMMm:    :MMMMMd        :MMd",
		" cMMm:  cMMm:        cMMm:     .cMMMd        :MMd",
		"  cMMm:  cMMm:      .cMMm:       .cMd        :MMd",
		"  cMMm:  :MMm:      cMMm:         .c         :MMd",
		"   cMMm:  :MMm:    cMMm:                     :MMd",
		"    cMMm:  :MMMMMMMMm:                      :MMd",
		"     cMMm:  :MMMMm:                        :MMd",
		"      cMMm:                               :MMd",
		"        cMMm:                           :MMd",
		"          cMMMMMMMMMMMMMMMMMMMMMMMMMMd",
	},
	"centos": {
		"                 ..",
		"               .PLTJ.",
		"              <><><><>",
		"     KKSSV' 4KKK LJ KKKL.'VSSKK",
		"     KKV' 4KKKKK LJ KKKKAL 'VKK",
		"     V' ' 'VKKKK LJ KKKKV' ' 'V",
		"     .4MA.' 'VKK LJ KKV' '.4Mb.",
		"   . KKKKKA.' 'V LJ V' '.4KKKKK .",
		" .4D KKKKKKKA.'' LJ ''.4KKKKKKK FA.",
		"<QDD ++++++++++++  ++++++++++++ GFD>",
		" 'VD KKKKKKKK'.. LJ ..'KKKKKKKK FV",
		"   ' VKKKKK'. .4 LJ K. .'KKKKKV '",
		"      'VK'. .4KK LJ KKA. .'KV'",
		"     A. . .4KKKK LJ KKKKA. . .4",
		"     KKA. 'KKKKK LJ KKKKK' .4KK",
		"     KKSSA. VKKK LJ KKKV .4SSKK",
		"              <><><><>",
		"               'MKKM'",
		"                 ''",
	},
	"freebsd": {
		"```                        `",
		"  ` `.....---...` ...--.```   -/",
		"  +o   .--`         /y:`      +.",
		"   yo`:.            :o      `+-",
		"    y/               -/`   -o/",
		"   .-                  ::/sy+:.",
		"   /                     `--  /",
		"  `:                          :`",
		"  `:                          :`",
		"   /                          /",
		"   .-                        -.",
		"    --                      -.",
		"     `:`                  `:`",
		"       .--             `--.",
		"          .---.....----.",
	},
	"openbsd": {
		"                                     _",
		"                                    (_)",
		"              |    .",
		"          .   |L  /|   .          _",
		"      _ . |\\ _| \\--+._/| .       (_)",
		"     / ||\\| Y J  )   / |/| ./",
		"    J  |)'( |        ` F`.'/        _",
		"  -<|  F         __     .-<        (_)",
		"    | /       .-'. `.  /-. L___",
		"    J \\      <    \\  | | O\\|.-'   _",
		"  _J \\  .-    \\/ O | | \\  |F    (_)",
		" '-F  -<_.     \\   .-'  `-' L__",
		"__J  _   _.     >-'  )._.   |-'",
		" `-|.'   /_.          \\_|   F",
		"  /.-   .                _.<",
		" /'    /.'             .'  `\\",
		"  /L  /'   |/      _.-'-\\",
		" /'J       ___.---'\\|",
		"   |\\  .--' V  | `. `",
		"   |/`. `-.     `._)",
		"      / .-.\\",
		"      \\ (  `\\",
		"       `.\\",
	},
	"netbsd": {
		"                     `-/oshdmNMNdhyo+:-`",
		"y/s+:-``    `.-:+oydNMMMMNhs/-``",
		"-m+NMMMMMMMMMMMMMMMMMMMNdhmNMMMmdhs+/-`",
		" -m+NMMMMMMMMMMMMMMMMMMMMmy+:`",
		"  -N/dMMMMMMMMMMMMMMMds:`",
		"   -N/hMMMMMMMMMmho:`",
		"    -N/-:/++/:.`",
		"     :M+",
		"      :Mo",
		"       :Ms",
		"        :Ms",
		"         :Ms",
		"          :Ms",
		"           :Ms",
		"            :Ms",
		"             :Ms",
		"              :Ms",
	},
	"nixos": {
		"          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖",
		"          ▜███▙       ▜███▙  ▟███▛",
		"           ▜███▙       ▜███▙▟███▛",
		"            ▜███▙       ▜██████▛",
		"     ▟█████████████████▙ ▜████▛     ▟▙",
		"    ▟███████████████████▙ ▜███▙    ▟██▙",
		"           ▄▄▄▄▖           ▜███▙  ▟███▛",
		"          ▟███▛             ▜██▛ ▟███▛",
		"         ▟███▛               ▜▛ ▟███▛",
		"▟███████████▛                  ▟██████████▙",
		"▜██████████▛                  ▟███████████▛",
		"      ▟███▛ ▟▙               ▟███▛",
		"     ▟███▛ ▟██▙             ▟███▛",
		"    ▟███▛  ▜███▙           ▝▀▀▀▀",
		"    ▜██▛    ▜███▙ ▜██████████████████▛",
		"     ▜▛     ▟████▙ ▜████████████████▛",
		"           ▟██████▙         ▜███▙",
		"          ▟███▛▜███▙         ▜███▙",
		"         ▟███▛  ▜███▙         ▜███▙",
		"         ▝▀▀▀    ▀▀▀▀▘         ▀▀▀▘",
	},
	"void": {
		"                __.;=====;.__",
		"            _.=+==++=++=+=+===;.",
		"             -=+++=+===+=+=+++++=_",
		"        .     -=:``     `--==+=++==.",
		"       _vi,    `            --+=++++:",
		"      .uvnvi.       _._       -==+==+.",
		"     .vvnvnI`    .;==|==;.     :|=||=|.",
		"+QmQQmpvvnv; _yYsyQQWUUQQQm #QmQ#:QQQWUV$QQm.",
		" -QQWQWpvvowZ?.wQQQE==<QWWQ/QWQW.QQWW(: jQWQE",
		"  -$QQQQmmU'  jQQQ@+=<QWQQ)mQQQ.mQQQC+;jWQQ@'",
		"   -$WQ8YnI:   QWQQwgQQWV`mWQQ.jQWQQgyyWW@!",
		"     -1vvnvv.     `~+++`        ++|+++",
		"      +vnvnnv,                 `-|===",
		"       +vnvnvns.           .      :=-",
		"        -Invnvvnsi..___..=sv=.     `",
		"          +Invnvnvnnnnnnnnvvnn;.",
		"            ~|Invnvnvvnvvvnnv}+`",
		"               -~|{*l}*|~",
	},
	"pop": {
		"             /////////////",
		"         /////////////////////",
		"      ///////\\*767////////////////",
		"    //////7676767676*//////////////",
		"   /////76767//7676767//////////////",
		"  /////767676///\\*76767///////////////",
		" ///////767676///76767.///7676*///////",
		"/////////767676//76767///767676////////",
		"//////////767676767676////76767/////////",
		"///////////767676767//////7676//////////",
		"////////////,7676,///////767///////////",
		"/////////////\\*7676///////76////////////",
		"///////////////7676////////////////////",
		" ///////////////7676///767////////////",
		"  //////////////////////'////////////",
		"   //////.7676767676767676767,//////",
		"    /////767676767676767676767/////",
		"      ///////////////////////////",
		"         /////////////////////",
		"             /////////////",
	},

	"kali": {
		"..............",
		"            ..,;:ccc,.",
		"          ......''';lxO.",
		".....''''..........,:ld;",
		"           .';;;:::;,,.x,",
		"      ..'''.            0Xxoc:,.  ...",
		"  ....                ,ONkc;,;cokOdc',.",
		" .                   OMo           ':ddo.",
		"                    dMc               :OO;",
		"                    0M.                 .:o.",
		"                    ;Wd",
		"                     ;XO,",
		"                       ,d0Odlc;,..",
		"                           ..',;:cdOOd::,.",
		"                                    .:d;.':;.",
		"                                       'd,  .'",
		"                                         ;l   ..",
		"                                          .o",
		"                                            c",
		"                                            .'",
		"                                             .",
	},
	"zorin": {
		"        `osssssssssssssssssssso`",
		"       .osssssssssssssssssssssso.",
		"      .+oooooooooooooooooooooooo+.",
		"",
		"",
		"  `::::::::::::::::::::::.         .:`",
		" `+ssssssssssssssssss+:.`     `.:+ssso`",
		".ossssssssssssssso/.       `-+ossssssso.",
		"ssssssssssssso/-`      `-/osssssssssssss",
		".ossssssso/-`      .-/ossssssssssssssso.",
		" `+sss+:.      `.:+ssssssssssssssssss+`",
		"  `:.         .::::::::::::::::::::::`",
		"",
		"",
		"      .+oooooooooooooooooooooooo+.",
		"       -osssssssssssssssssssssso-",
		"        `osssssssssssssssssssso`",
	},
	"mx": {
		"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMM",
		"MMMMMMMMMMNs..yMMMMMMMMMMMMMm: +NMMMMMMM",
		"MMMMMMMMMN+    :mMMMMMMMMMNo` -dMMMMMMMM",
		"MMMMMMMMMMMs.   `oNMMMMMMh- `sNMMMMMMMMM",
		"MMMMMMMMMMMMN/    -hMMMN+  :dMMMMMMMMMMM",
		"MMMMMMMMMMMMMMh-    +ms. .sMMMMMMMMMMMMM",
		"MMMMMMMMMMMMMMMN+`   `  +NMMMMMMMMMMMMMM",
		"MMMMMMMMMMMMMMNMMd:    .dMMMMMMMMMMMMMMM",
		"MMMMMMMMMMMMm/-hMd-     `sNMMMMMMMMMMMMM",
		"MMMMMMMMMMNo`   -` :h/    -dMMMMMMMMMMMM",
		"MMMMMMMMMd:       /NMMh-   `+NMMMMMMMMMM",
		"MMMMMMMNo`         :mMMN+`   `-hMMMMMMMM",
		"MMMMMMh.            `oNMMd:    `/mMMMMMM",
		"MMMMm/                -hMd-      `sNMMMM",
		"MMNs`                   -          :dMMM",
		"Mm:                                 `oMM",
		"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	},
	"neon": {
		"             `..---+/---..`",
		"         `---.``   ``   `.---.`",
		"      .--.`        ``        `-:-.",
		"    `:/:     `.----//----.`     :/-",
		"   .:.    `---`          `--.`    .:`",
		"  .:`   `--`                .:-    `:.",
		" `/    `:.      `.-::-.`      -:`   `/`",
		" /.    /.     `:++++++++:`     .:    .:",
		"`/    .:     `+++++++++++/      /`   `+`",
		"/+`   --     .++++++++++++`     :.   .+:",
		"`/    .:     `+++++++++++/      /`   `+`",
		" /`    /.     `:++++++++:`     .:    .:",
		" ./    `:.      `.:::-.`      -:`   `/`",
		"  .:`   `--`                .:-    `:.",
		"   .:.    `---`          `--.`    .:`",
		"    `:/:     `.----//----.`     :/-",
		"      .-:.`        ``        `-:-.",
		"         `---.``   ``   `.---.`",
		"             `..---+/---..`",
	},
	"elementary": {
		"         eeeeeeeeeeeeeeeee",
		"      eeeeeeeeeeeeeeeeeeeeeee",
		"    eeeee  eeeeeeeeeeee   eeeee",
		"  eeee   eeeee       eee     eeee",
		" eeee   eeee          eee     eeee",
		"eee    eee            eee       eee",
		"eee   eee            eee        eee",
		"ee    eee           eeee       eeee",
		"ee    eee         eeeee      eeeeee",
		"ee    eee       eeeee      eeeee ee",
		"eee   eeee   eeeeee      eeeee  eee",
		"eee    eeeeeeeeee     eeeeee    eee",
		" eeeeeeeeeeeeeeeeeeeeeeee    eeeee",
		"  eeeeeeee eeeeeeeeeeee      eeee",
		"    eeeee                 eeeee",
		"      eeeeeee         eeeeeee",
		"         eeeeeeeeeeeeeeeee",
	},
	"endeavouros": {
		"                     ./o.",
		"                   ./sssso-",
		"                 `:osssssss+-",
		"               `:+sssssssssso/.",
		"             `-/ossssssssssssso/.",
		"           `-/+sssssssssssssssso+:`",
		"         `-:/+sssssssssssssssssso+/.",
		"       `.://osssssssssssssssssssso++-",
		"      .://+ssssssssssssssssssssssso++:",
		"    .:///ossssssssssssssssssssssssso++:",
		"  `:////ssssssssssssssssssssssssssso+++.",
		"`-////+ssssssssssssssssssssssssssso++++-",
		" `..-+oosssssssssssssssssssssssso+++++/`",
		"   ./++++++++++++++++++++++++++++++/:.",
		"  `:::::::::::::::::::::::::------``",
	},
	"garuda": {
		"                   .%;888:8898898:",
		"                 x;XxXB%89b8:b8%b88:",
		"              .8Xxd                8X:.",
		"            .8Xx;                    8x:.",
		"          .tt8x          .d            x88;",
		"       .@8x8;          .db:              xx@;",
		"     ,tSXX°          .bbbbbbbbbbbbbbbbbbbB8x@;",
		"   .SXxx            bBBBBBBBBBBBBBBBBBBBbSBX8;",
		" ,888S                                     pd!",
		"8X88/                                       q",
		"8X88/",
		"GBB.",
		" x%88        d888@8@X@X@X88X@@XX@@X@8@X.",
		"   dxXd    dB8b8b8B8B08bB88b998888b88x.",
		"    dxx8o                      .@@;.",
		"      dx88                   .t@x.",
		"        d:SS@8ba89aa67a853Sxxad.",
		"          .d988999889889899dd.",
	},
	"cachyos": {
		"           .-------------------------:",
		"          .+=========================.",
		"         :++===++==================-       :++-",
		"        :*++====+++++=============-        .==:",
		"       -*+++=====+***++==========:",
		"      =*++++========------------:",
		"     =*+++++=====-                     ...",
		"   .+*+++++=-===:                    .=+++=:",
		"  :++++=====-==:                     -*****+",
		" :++========-=.                      .=+**+.",
		".+==========-.                          .",
		" :+++++++====-                                .--==-.",
		"  :++==========.                             :+++++++:",
		"   .-===========.                            =*****+*+",
		"    .-===========:                           .+*****+:",
		"      -=======++++:::::::::::::::::::::::::-:  .---:",
		"       :======++++====+++******************=.",
		"        :=====+++==========++++++++++++++*-",
		"         .====++==============++++++++++*-",
		"          .===+==================+++++++:",
		"           .-=======================+++:",
		"             ..........................",
	},
	"bazzite": {
		"     %%%%%%====%%%%%%%%%%            ",
		"   %%%%%%%%    %%%%%%%%%%%%%%        ",
		"  %%%%%%%%%    %%%%%%%%%%%%%%%%      ",
		"  %%%%%%%%%    %%%%%%%%%%%%%%%###    ",
		"  %%%%%%%%%    %%%%%%%%%%%%%######   ",
		"  ==                  =======######  ",
		"  ==                  =========##### ",
		"  %%%%%%%%%    %%%%%%%####======#####",
		"  %%%%%%%%%    %%%%%#######=====#####",
		"  %%%%%%%%%    %%%#########=====#####",
		"  %%%%%%%%%    %%##########=====#####",
		"  %%%%%%%%%====###########=====######",
		"   %%%%%%%%====#########======###### ",
		"    %%%%%%%=====#####========######  ",
		"     %%%%###===============#######   ",
		"      %#######==========#########    ",
		"        #######################      ",
		"          ###################        ",
		"              ###########            ",
	},
	"steamos": {
		"              .,,,,.",
		"        .,'onNMMMMMNNnn',.",
		"     .'oNMANKMMMMMMMMMMMNNn'.",
		"   .'ANMMMMMMMXKNNWWWPFFWNNMNn.",
		"  ;NNMMMMMMMMMMNWW'' ,.., 'WMMM,",
		" ;NMMMMV+##+VNWWW' .+;'':+, 'WMW,",
		",VNNWP+######+WW,  +:    :+, +MMM,",
		"'+#############,   +.    ,+' +NMMM",
		"  '*#########*'     '*,,*' .+NMMMM.",
		"     `'*###*'          ,.,;###+WNM,",
		"         .,;;,      .;##########+W",
		",',.         ';  ,+##############'",
		" '###+. :,. .,; ,###############'",
		"  '####.. `'' .,###############'",
		"    '#####+++################'",
		"      '*##################*'",
		"         ''*##########*''",
		"              ''''''",
	},
	"parrot": {
		"  `:oho/-`",
		"`mMMMMMMMMMMMNmmdhy-",
		" dMMMMMMMMMMMMMMMMMMs`",
		" +MMsohNMMMMMMMMMMMMMm/",
		" .My   .+dMMMMMMMMMMMMMh.",
		"  +       :NMMMMMMMMMMMMNo",
		"           `yMMMMMMMMMMMMMm:",
		"             /NMMMMMMMMMMMMMy`",
		"              .hMMMMMMMMMMMMMN+",
		"                  ``-NMMMMMMMMMd-",
		"                     /MMMMMMMMMMMs`",
		"                      mMMMMMMMsyNMN/",
		"                      +MMMMMMMo  :sNh.",
		"                      `NMMMMMMm     -o/",
		"                       oMMMMMMM.",
		"                       `NMMMMMM+",
		"                        +MMd/NMh",
		"                         mMm -mN`",
		"                         /MM  `h:",
		"                          dM`   .",
		"                          :M-",
		"                           d:",
		"                           -+",
		"                            -",
	},
	"deepin": {
		"             ............",
		"         .';;;;;.       .,;,.",
		"      .,;;;;;;;.       ';;;;;;;.",
		"    .;::::::::'     .,::;;,''''',.",
		"   ,'.::::::::    .;;'.          ';",
		"  ;'  'cccccc,   ,' :: '..        .:",
		" ,,    :ccccc.  ;: .c, '' :.       ,;",
		".l.     cllll' ., .lc  :; .l'       l.",
		".c       :lllc  ;cl:  .l' .ll.      :'",
		".l        'looc. .   ,o:  'oo'      c,",
		".o.         .:ool::coc'  .ooo'      o.",
		" ::            .....   .;dddo      ;c",
		"  l:...            .';lddddo.     ,o",
		"   lxxxxxdoolllodxxxxxxxxxc      :l",
		"    ,dxxxxxxxxxxxxxxxxxxl.     'o,",
		"      ,dkkkkkkkkkkkkko;.    .;o;",
		"        .;okkkkkdl;.    .,cl:.",
		"            .,:cccccccc:,.",
	},
	"tails": {
		"      ``",
		"  ./yhNh",
		"syy/Nshh         `:o/",
		"N:dsNshh  █   `ohNMMd",
		"N-/+Nshh      `yMMMMd",
		"N-yhMshh       yMMMMd",
		"N-s:hshh  █    yMMMMd so//.",
		"N-oyNsyh       yMMMMd d  Mms.",
		"N:hohhhd:.     yMMMMd  syMMM+",
		"Nsyh+-..+y+-   yMMMMd   :mMM+",
		"+hy-      -ss/`yMMMM     `+d+",
		"  :sy/.     ./yNMMMMm      ``",
		"    .+ys- `:+hNMMMMMMy/`",
		"      `hNmmMMMMMMMMMMMMdo.",
		"       dMMMMMMMMMMMMMMMMMNh:",
		"       +hMMMMMMMMMMMMMMMMMmy.",
		"         -oNMMMMMMMMMMmy+.`",
		"           `:yNMMMds/.`",
		"              .//`",
	},
	"qubes": {
		"               `..--..`",
		"            `.----------.`",
		"        `..----------------..`",
		"     `.------------------------.``",
		" `..-------------....-------------..`",
		".::----------..``    ``..----------:+:",
		":////:----..`            `..---:/ossso",
		":///////:`                  `/osssssso",
		":///////:                    /ssssssso",
		":///////:                    /ssssssso",
		":///////:                    /ssssssso",
		":///////:                    /ssssssso",
		":///////:                    /ssssssso",
		":////////-`                .:sssssssso",
		":///////////-.`        `-/osssssssssso",
		"`//////////////:-```.:+ssssssssssssso-",
		"  .-://////////////sssssssssssssso/-`",
		"     `.:///////////sssssssssssssso:.",
		"         .-:///////ssssssssssssssssss/`",
		"            `.:////ssss+/+ssssssssssss.",
		"                `--//-    `-/osssso/.",
	},
	"rocky": {
		"          __wgliliiligw_,",
		"       _williiiiiiliilililw,",
		"     _%iiiiiilililiiiiiiiiiii_",
		"   .Qliiiililiiiiiiililililiilm.",
		"  _iiiiiliiiiiililiiiiiiiiiiliil,",
		" .lililiiilililiiiilililililiiiii,",
		"_liiiiiiliiiiiiiliiiiiF{iiiiiilili,",
		"jliililiiilililiiili@`  ~ililiiiiiL",
		"iiiliiiiliiiiiiili>`      ~liililii",
		"liliiiliiilililii`         -9liiiil",
		"iiiiiliiliiiiii~             \\\"4lili",
		"4ililiiiiilil~|      -w,       )4lf",
		"-liiiiililiF'       _liig,       )'",
		" )iiiliii@`       _QIililig,",
		"  )iiii>`       .Qliliiiililw",
		"   )<>~       .mliiiiiliiiiiil,",
		"            _gllilililiililii~",
		"           giliiiiiiiiiiiiT`",
		"          -^~$ililili@~~'",
	},
	"almalinux": {
		"         'c:.",
		"        lkkkx, ..       ..   ,cc,",
		"        okkkk:ckkx'  .lxkkx.okkkkd",
		"        .:llcokkx'  :kkkxkko:xkkd,",
		"      .xkkkkdood:  ;kx,  .lkxlll;",
		"       xkkx.       xk'     xkkkkk:",
		"       'xkx.       xd      .....,.",
		"      .. :xkl'     :c      ..''..",
		"    .dkx'  .:ldl:'. '  ':lollldkkxo;",
		"  .''lkkko'                     ckkkx.",
		"'xkkkd:kkd.       ..  ;'        :kkxo.",
		",xkkkd;kk'      ,d;    ld.   ':dkd::cc,",
		" .,,.;xkko'.';lxo.      dx,  :kkk'xkkkkc",
		"     'dkkkkkxo:.        ;kx  .kkk:;xkkd.",
		"       .....   .;dk:.   lkk.  :;,",
		"             :kkkkkkkdoxkkx",
		"              ,c,,;;;:xkkd.",
		"                ;kkkkl...",
		"                ;kkkkl",
		"                 ,od;",
	},
	"oracle": {
		"      `-/+++++++++++++++++/-.`",
		"   `/syyyyyyyyyyyyyyyyyyyyyyys/.",
		"  :yyyyo/-...............-/oyyyy/",
		" /yyys-                     .oyyy+",
		".yyyy`                       `syyy-",
		":yyyo                         /yyy/",
		".yyyy`                       `syyy-",
		" /yyys.                     .oyyyo",
		"  /yyyyo:-...............-:oyyyy/`",
		"   `/syyyyyyyyyyyyyyyyyyyyyyys+.",
		"     `.:/+ooooooooooooooo+/:.`",
	},
	"solus": {
		"            -```````````",
		"          `-+/------------.`",
		"       .---:mNo---------------.",
		"     .-----yMMMy:---------------.",
		"   `------oMMMMMm/----------------`",
		"  .------/MMMMMMMN+----------------.",
		" .------/NMMMMMMMMm-+/--------------.",
		"`------/NMMMMMMMMMN-:mh/-------------`",
		".-----/NMMMMMMMMMMM:-+MMd//oso/:-----.",
		"-----/NMMMMMMMMMMMM+--mMMMh::smMmyo:--",
		"----+NMMMMMMMMMMMMMo--yMMMMNo-:yMMMMd/.",
		".--oMMMMMMMMMMMMMMMy--yMMMMMMh:-yMMMy-`",
		"`-sMMMMMMMMMMMMMMMMh--dMMMMMMMd:/Ny+y.",
		"`-/+osyhhdmmNNMMMMMm-/MMMMMMMmh+/ohm+",
		"  .------------:://+-/++++++oshddys:",
		"   -hhhhyyyyyyyyyyyhhhhddddhysssso-",
		"    `:ossssssyysssssssssssssssso:`",
		"      `:+ssssssssssssssssssss+-",
		"         `-/+ssssssssssso+/-`",
		"              `.-----..`",
	},
	"puppy": {
		"           `-/osyyyysosyhhhhhyys+-",
		"  -ohmNNmh+/hMMMMMMMMNNNNd+dMMMMNM+",
		" yMMMMNNmmddo/NMMMNNNNNNNNNo+NNNNNy",
		".NNNNNNmmmddds:MMNNNNNNNNNNNh:mNNN/",
		"-NNNdyyyhdmmmd`dNNNNNmmmmNNmdd/os/",
		".Nm+shddyooo+/smNNNNmmmmNh.   :mmd.",
		" NNNNy:`   ./hmmmmmmmNNNN:     hNMh",
		" NMN-    -++- +NNNNNNNNNNm+..-sMMMM-",
		".MMo    oNNNNo hNNNNNNNNmhdNNNMMMMM+",
		".MMs    /NNNN/ dNmhs+:-`  yMMMMMMMM+",
		" mMM+     .. `sNN+.      hMMMMhhMMM-",
		" +MMMmo:...:sNMMMMMms:` hMMMMm.hMMy",
		"  yMMMMMMMMMMMNdMMMMMM::/+o+//dMMd`",
		"   sMMMMMMMMMMN+:oyyo:sMMMNNMMMNy`",
		"    :mMMMMMMMMMMMmddNMMMMMMMMmh/",
		"      /dMMMMMMMMMMMMMMMMMMNdy/`",
		"        .+hNMMMMMMMMMNmdhs/.",
		"            .:/+ooo+/:-.",
	},
	"peppermint": {
		"             PPPPPPPPPPPPPP",
		"         PPPPMMMMMMMPPPPPPPPPPP",
		"       PPPPMMMMMMMMMMPPPPPPPPMMPP",
		"     PPPPPPPPMMMMMMMPPPPPPPPMMMMMPP",
		"   PPPPPPPPPPPPMMMMMMPPPPPPPMMMMMMMPP",
		"  PPPPPPPPPPPPMMMMMMMPPPPMPMMMMMMMMMPP",
		" PPMMMMPPPPPPPPPPMMMPPPPPMMMMMMMPMMPPPP",
		" PMMMMMMMMMMPPPPPPMMPPPPPMMMMMMPPPPPPPP",
		"PMMMMMMMMMMMMPPPPPMMPPMPMMPMMPPPPPPPPPPP",
		"PMMMMMMMMMMMMMMMMPPMPMMMPPPPPPPPPPPPPPPP",
		"PMMMPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMP",
		"PPPPPPPPPPPPPPPPMMMPMPMMMMMMMMMMMMMMMMPP",
		"PPPPPPPPPPPMMPMMPPPPMMPPPPPMMMMMMMMMMMPP",
		" PPPPPPPPMMMMMMPPPPPMMPPPPPPMMMMMMMMMPP",
		" PPPPMMPMMMMMMMPPPPPPMMPPPPPPPPPPMMMMPP",
		"  PPMMMMMMMMMPMPPPPMMMMMMPPPPPPPPPPPPP",
		"   PPMMMMMMMPPPPPPPMMMMMMPPPPPPPPPPPP",
		"     PPMMMMPPPPPPPPPMMMMMMMPPPPPPPP",
		"       PPMMPPPPPPPPMMMMMMMMMMPPPP",
		"         PPPPPPPPPPMMMMMMMMPPPP",
		"             PPPPPPPPPPPPPP",
	},
	"antix": {
		"                    \\\\",
		"         , - ~ ^ ~ - \\\\        /",
		"     , '              \\\\ ' ,  /",
		"   ,                   \\\\   '/",
		"  ,                     \\\\  / ,",
		" ,___,                   \\\\/   ,",
		" /   |   _  _  _|_ o     /\\\\   ,",
		"|,   |  / |/ |  |  |    /  \\\\  ,",
		" \\\\,_/\\\\_/  |  |_/|_/|_/_/    \\\\,",
		"   ,                  /     ,\\\\",
		"     ,               /  , '   \\\\",
		"      ' - , _ _ _ ,  '",
	},
	"nobara": {
		"⢀⣤⣴⣶⣶⣶⣦⣤⡀⠀⣀⣠⣤⣴⣶⣶⣶⣶⣶⣶⣶⣶⣤⣤⣀⡀",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⡀",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠋⠉⠁⠀⠀⠉⠉⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠁⠀⠀⠀⢀⣀⣀⡀⠀⠀⠀⠈⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠀⠀⠀⢠⣾⣿⣿⣿⣿⣷⡄⠀⠀⠀⠻⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⣀⣀⣬⣽⣿⣿⣿⣿⣿⣿",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠈⠻⢿⣿⣿⡿⠟⠁⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⣤⣄⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿",
		"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠛⠉⠉⠛⠛⢿⣿⣿⠀⠀⠀⠀⠀⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿",
		"⠘⢿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⠟⠁",
		"  ⠈⠙⠛⠛⠛⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠛⠛⠛⠉⠁",
	},
	"clearlinux": {
		"          BBB",
		"       BBBBBBBBB",
		"     BBBBBBBBBBBBBBB",
		"   BBBBBBBBBBBBBBBBBBBB",
		"   BBBBBBBBBBB         BBB",
		"  BBBBBBBBYYYYY",
		"  BBBBBBBBYYYYYY",
		"  BBBBBBBBYYYYYYY",
		"  BBBBBBBBBYYYYYW",
		" GGBBBBBBBYYYYYWWW",
		" GGGBBBBBBBYYWWWWWWWW",
		" GGGGGGBBBBBBWWWWWWWW",
		" GGGGGGGGBBBBWWWWWWWW",
		"GGGGGGGGGGGBBBWWWWWWW",
		"GGGGGGGGGGGGGBWWWWWW",
		"GGGGGGGGWWWWWWWWWWW",
		"GGWWWWWWWWWWWWWWWW",
		" WWWWWWWWWWWWWWWW",
		"      WWWWWWWWWW",
		"          WWW",
	},
	"pclinuxos": {
		"            mhhhyyyyhhhdN",
		"        dyssyhhhhhhhhhhhssyhN",
		"     Nysyhhyo/:-.....-/oyhhhssd",
		"   Nsshhy+.              `/shhysm",
		"  dohhy/                    -shhsy",
		" dohhs`                       /hhys",
		"N+hho   +ssssss+-   .+syhys+   /hhsy",
		"ohhh`   ymmo++hmm+`smmy/::+y`   shh+",
		"+hho    ymm-  /mmy+mms          :hhod",
		"/hh+    ymmhhdmmh.smm/          .hhsh",
		"+hhs    ymm+::-`  /mmy`    `    /hh+m",
		"yyhh-   ymm-       /dmdyosyd`  `yhh+",
		" ohhy`  ://`         -/+++/-   ohhom",
		" N+hhy-                      `shhoh",
		"   sshho.                  `+hhyom",
		"    dsyhhs/.            `:ohhhoy",
		"      dysyhhhso///://+syhhhssh",
		"         dhyssyhhhhhhyssyyhN",
		"              mddhdhdmN",
	},
}
