package display

// DistroLogos contains the authentic, accurate ASCII art distro logos from neofetch/fastfetch.
var DistroLogos = map[string][]string{
	"arch": {
		"                  -`",
		"                 .o+`",
		"                `ooo/",
		"               `+oooo:",
		"              `+oooooo:",
		"              -+oooooo+:",
		"            `/:-:++oooo+:",
		"           `/++++/+++++++:",
		"          `/++++++++++++++:",
		"         `/+++ooooooooooooo/`",
		"        ./ooosssso++osssssso+`",
		"       .oossssso-````/ossssss+`",
		"      -osssssso.      :ssssssso.",
		"     :osssssss/        osssso+++.",
		"    /ossssssss/        +ssssooo/-",
		"  `/ossssso+/:-        -:/+osssso+-",
		" `+sso+:-`                 `.-/+oso:",
		"`++:.                           `-/+/",
		".`                                 `/",
	},
	"manjaro": {
		"██████████████████  ████████",
		"██████████████████  ████████",
		"██████████████████  ████████",
		"██████████████████  ████████",
		"████████            ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
		"████████  ████████  ████████",
	},
	"ubuntu": {
		"                             ....",
		"              .',:clooo:  .:looooo:.",
		"           .;looooooooc  .oooooooooo'",
		"        .;looooool:,''.  :ooooooooooc",
		"       ;looool;.         'oooooooooo,",
		"      ;clool'             .cooooooc.  ,,",
		"         ...                ......  .:oo,",
		"  .;clol:,.                        .loooo'",
		" :ooooooooo,                        'ooool",
		"'ooooooooooo.                        loooo.",
		"'ooooooooool                         coooo.",
		" ,loooooooc.                        .loooo.",
		"   .,;;;'.                          ;ooooc",
		"       ...                         ,ooool.",
		"    .cooooc.              ..',,'.  .cooo.",
		"      ;ooooo:.           ;oooooooc.  :l.",
		"       .coooooc,..      coooooooooo.",
		"         .:ooooooolc:. .ooooooooooo'",
		"           .':loooooo;  ,oooooooooc",
		"               ..';::c'  .;loooo:'",
	},
	"debian": {
		"        _,met$$$$$gg.",
		"     ,g$$$$$$$$$$$$$$$P.",
		"   ,g$$P\"\"       \"\"\"Y$$\".\"",
		"  ,$$P'              `$$$.",
		"',$$P       ,ggs.     `$$b:",
		"`d$$'     ,$P\"'   .    $$$",
		" $$P      d$'     ,    $$P",
		" $$:      $$.   -    ,d$$'",
		" $$;      Y$b._   _,d$P'",
		" Y$$.    `.`\"Y$$$$P\"'",
		" `$$b      \"-.__",
		"  `Y$$b",
		"   `Y$$.",
		"     `$$b.",
		"       `Y$$b.",
		"         `\"Y$b._",
		"             `\"\"\"\"",
	},
	"fedora": {
		"             .',;::::;,'..",
		"         .';:cccccccccccc:;,.",
		"      .;cccccccccccccccccccccc;.",
		"    .:cccccccccccccccccccccc:.",
		"  .;ccccccccccccc;.:dddl:.;ccccccc;.",
		" .:ccccccccccccc;OWMKOOXMWd;ccccccc:.",
		".:ccccccccccccc;KMMc;cc;xMMc;ccccccc:.",
		",cccccccccccccc;MMM.;cc;;WW:;cccccccc,",
		":cccccccccccccc;MMM.;cccccccccccccccc:",
		":ccccccc;oxOOOo;MMM000k.;cccccccccccc:",
		"cccccc;0MMKxdd:;MMMkddc.;cccccccccccc;",
		"ccccc;XMO';cccc;MMM.;cccccccccccccccc'",
		"ccccc;MMo;ccccc;MMW.;ccccccccccccccc;",
		"ccccc;0MNc.ccc.xMMd;ccccccccccccccc;",
		"cccccc;dNMWXXXWM0:;cccccccccccccc:,",
		"cccccccc;.:odl:.;cccccccccccccc:,.",
		"ccccccccccccccccccccccccccccc:'.",
		":ccccccccccccccccccccccc:;,..",
		" ':cccccccccccccccc::;,,.",
	},
	"macos": {
		"                     ..'",
		"                 ,xNMM.",
		"               .OMMMMo",
		"               lMM\"",
		"     .;loddo:.  .olloddol;.",
		"   cKMMMMMMMMMMNWMMMMMMMMMM0:",
		" .KMMMMMMMMMMMMMMMMMMMMMMMWd.",
		" XMMMMMMMMMMMMMMMMMMMMMMMX.",
		";MMMMMMMMMMMMMMMMMMMMMMMM:",
		":MMMMMMMMMMMMMMMMMMMMMMMM:",
		".MMMMMMMMMMMMMMMMMMMMMMMMX.",
		" kMMMMMMMMMMMMMMMMMMMMMMMMWd.",
		" 'XMMMMMMMMMMMMMMMMMMMMMMMMMMk",
		"  'XMMMMMMMMMMMMMMMMMMMMMMMMK.",
		"    kMMMMMMMMMMMMMMMMMMMMMMd",
		"     ;KMMMMMMMWXXWMMMMMMMk.",
		"       \"cooc*\"    \"*coo'\"",
	},
	"windows": {
		"        ,.=:!!t3Z3z.,",
		"       :tt:::tt333EE3",
		"       Et:::ztt33EEEL @Ee.,      ..,",
		"      ;tt:::tt333EE7 ;EEEEEEttttt33#",
		"     :Et:::zt333EEQ. $EEEEEttttt33QL",
		"     it::::tt333EEF @EEEEEEttttt33F",
		"    ;3=*^```\"*4EEV :EEEEEEttttt33@.",
		"    ,.=::::!t=., ` @EEEEEEtttz33QF",
		"   ;::::::::zt33)   \"4EEEtttji3P*",
		"  :t::::::::tt33.:Z3z..  `` ,..g.",
		"  i::::::::zt33F AEEEtttt::::ztF",
		" ;:::::::::t33V ;EEEttttt::::t3",
		" E::::::::zt33L @EEEtttt::::z3F",
		"{3=*^```\"*4E3) ;EEEtttt:::::tZ`",
		"             ` :EEEEtttt::::z7",
		"                 \"VEzjt:;;z>*`",
	},
	"linux": {
		"        #####",
		"       #######",
		"       ##O#O##",
		"       #######",
		"     ###########",
		"    #############",
		"   ###############",
		"   ################",
		"  #################",
		"#####################",
		"#####################",
		"  #################",
	},
	"alpine": {
		"       .hddddddddddddddddddddddh.",
		"      :dddddddddddddddddddddddddd:",
		"     /dddddddddddddddddddddddddddd/",
		"    +dddddddddddddddddddddddddddddd+",
		"  `sdddddddddddddddddddddddddddddddds`",
		" `ydddddddddddd++hdddddddddddddddddddy`",
		".hddddddddddd+`  `+ddddh:-sdddddddddddh.",
		"hdddddddddd+`      `+y:    .sddddddddddh",
		"ddddddddh+`   `//`   `.`     -sddddddddd",
		"ddddddh+`   `/hddh/`   `:s-    -sddddddd",
		"ddddh+`   `/+/dddddh/`   `+s-    -sddddd",
		"ddd+`   `/o` :dddddddh/`   `oy-    .yddd",
		"hdddyo+ohddyosdddddddddho+oydddy++ohdddh",
		".hddddddddddddddddddddddddddddddddddddh.",
		" `yddddddddddddddddddddddddddddddddddy`",
		"  `sdddddddddddddddddddddddddddddddds`",
		"    +dddddddddddddddddddddddddddddd+",
		"     /dddddddddddddddddddddddddddd/",
		"      :dddddddddddddddddddddddddd:",
		"       .hddddddddddddddddddddddh.",
	},
	"gentoo": {
		"         -/oyddmdhs+:.",
		"     -odNMMMMMMMMNNmhy+-`",
		"   -yNMMMMMMMMMMMNNNmmdhy+-",
		" `omMMMMMMMMMMMMNmdmmmmddhhy/`",
		" omMMMMMMMMMMMNhhyyyohmdddhhhdo`",
		".ydMMMMMMMMMMdhs++so/smdddhhhhdm+`",
		" oyhdmNMMMMMMMNdyooydmddddhhhhyhNd.",
		"  :oyhhdNNMMMMMMMNNNmmdddhhhhhyymMh",
		"    .:+sydNMMMMMNNNmmmdddhhhhhhmMmy",
		"       /mMMMMMMNNNmmmdddhhhhhmMNhs:",
		"    `oNMMMMMMMNNNmmmddddhhdmMNhs+`",
		"  `sNMMMMMMMMNNNmmmdddddmNMmhs/.",
		" /NMMMMMMMMNNNNmmmdddmNMNdso:`",
		"+MMMMMMMNNNNNmmmmdmNMNdso/-",
		"yMMNNNNNNNmmmmmNNMmhs+/-`",
		"/hMMNNNNNNNNMNdhs++/-`",
		"`/ohdmmddhys+++/:.`",
		"  `-//////:--.",
	},
	"redhat": {
		"           .MMM..:MMMMMMM",
		"          MMMMMMMMMMMMMMMMMM",
		"          MMMMMMMMMMMMMMMMMMMM.",
		"         MMMMMMMMMMMMMMMMMMMMMM",
		"        ,MMMMMMMMMMMMMMMMMMMMMM:",
		"        MMMMMMMMMMMMMMMMMMMMMMMM",
		"  .MMMM'  MMMMMMMMMMMMMMMMMMMMMM",
		" MMMMMM    `MMMMMMMMMMMMMMMMMMMM.",
		"MMMMMMMM      MMMMMMMMMMMMMMMMMM .",
		"MMMMMMMMM.       `MMMMMMMMMMMMM' MM.",
		"MMMMMMMMMMM.                     MMMM",
		"`MMMMMMMMMMMMM.                 ,MMMMM.",
		" `MMMMMMMMMMMMMMMMM.          ,MMMMMMMM.",
		"    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
		"      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:",
		"         MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
		"            `MMMMMMMMMMMMMMMMMMMMMMMM:",
		"                ``MMMMMMMMMMMMMMMMM'",
	},
	"opensuse": {
		"           .;ldkO0000Okdl;.",
		"       .;d00xl:^''''''^:ok00d;.",
		"     .d00l'                'o00d.",
		"   .d0Kd'  Okxol:;,.          :O0d",
		"  .OKKKK0kOKKKKKKKKKKOxo:,      lKO.",
		" ,0KKKKKKKKKKKKKKKK0P^,,,^dx:    ;00,",
		".OKKKKKKKKKKKKKKKKk'.oOPPb.'0k.   cKO.",
		":KKKKKKKKKKKKKKKKK: kKx..dd lKd   'OK:",
		"dKKKKKKKKKKKOx0KKKd ^0KKKO' kKKc   dKd",
		"dKKKKKKKKKKKK;.;oOKx,..^..;kKKK0.  dKd",
		":KKKKKKKKKKKK0o;...^cdxxOK0O/^^'  .0K:",
		" kKKKKKKKKKKKKKKK0x;,,......,;od  lKk",
		" '0KKKKKKKKKKKKKKKKKKKKK00KKOo^  c00'",
		"  'kKKKOxddxkOO00000Okxoc;''   .dKk'",
		"    l0Ko.                    .c00l'",
		"     'l0Kk:.              .;xK0l'",
		"        'lkK0xl:;,,,,;:ldO0kl'",
		"            '^:ldxkkkkxdl:^'",
	},
	"mint": {
		"          cMMMMMMMMMMMMMMMMMMMMMMMMMMd",
		"        cMMm:                        :MMd",
		"      cMMm:                            :MMd",
		"     cMMm:  .cMMMMMMMMMMMMMMMMMMMMMMd.  :MMd",
		"    cMMm:  cMMm:cMMMMMMMMMMMMMMMMMMMMMd  :MMd",
		"   cMMm:  cMMm:  :MMMMMMMMMMMMMMMMMMMMMd  :MMd",
		"  cMMm:  cMMm:    :MMMMMMMMMMMMMMMMMMMMMd  :MMd",
		" cMMm:  cMMm:      .cMMMMMMMMMMMMMMMMMMMMd  :MMd",
		" cMMm:  cMMm:        cMMMMMMMMMMMMMMd.       :MMd",
		" cMMm:  cMMm:        cMMm:cMMMMMMMMMd        :MMd",
		" cMMm:  cMMm:        cMMm:  :MMMMMMMd        :MMd",
		" cMMm:  cMMm:        cMMm:    :MMMMMd        :MMd",
		" cMMm:  cMMm:        cMMm:     .cMMMd        :MMd",
		"  cMMm:  cMMm:      .cMMm:       .cMd        :MMd",
		"  cMMm:  :MMm:      cMMm:         .c         :MMd",
		"   cMMm:  :MMm:    cMMm:                     :MMd",
		"    cMMm:  :MMMMMMMMm:                      :MMd",
		"     cMMm:  :MMMMm:                        :MMd",
		"      cMMm:                               :MMd",
		"        cMMm:                           :MMd",
		"          cMMMMMMMMMMMMMMMMMMMMMMMMMMd",
	},
	"centos": {
		"                 ..",
		"               .PLTJ.",
		"              <><><><>",
		"     KKSSV' 4KKK LJ KKKL.'VSSKK",
		"     KKV' 4KKKKK LJ KKKKAL 'VKK",
		"     V' ' 'VKKKK LJ KKKKV' ' 'V",
		"     .4MA.' 'VKK LJ KKV' '.4Mb.",
		"   . KKKKKA.' 'V LJ V' '.4KKKKK .",
		" .4D KKKKKKKA.'' LJ ''.4KKKKKKK FA.",
		"<QDD ++++++++++++  ++++++++++++ GFD>",
		" 'VD KKKKKKKK'.. LJ ..'KKKKKKKK FV",
		"   ' VKKKKK'. .4 LJ K. .'KKKKKV '",
		"      'VK'. .4KK LJ KKA. .'KV'",
		"     A. . .4KKKK LJ KKKKA. . .4",
		"     KKA. 'KKKKK LJ KKKKK' .4KK",
		"     KKSSA. VKKK LJ KKKV .4SSKK",
		"              <><><><>",
		"               'MKKM'",
		"                 ''",
	},
	"freebsd": {
		"```                        `",
		"  ` `.....---...` ...--/   -`",
		"  +o   .--`         /y:`      +",
		"   yo`:.            :o      `+-",
		"    y/               -/`   -o/",
		"   .-                  ::/sy+:",
		"   /                     `--  /",
		"  `:                          :`",
		"  `:                          :`",
		"   /                          /",
		"   .-                        -.",
		"    --                      --",
		"     `//`                `//`",
		"       `++-`          `++-`",
		"          `/+++----+++/`",
		"              :+++\\`",
	},
	"openbsd": {
		"                                       _  ",
		"                                      (_) ",
		"               (_)                        ",
		"   ___   _ __   _ _ __   ___ ___   _   ___",
		"  / _ \\ | '_ \\ | | '_ \\ / __/ __| | | / __|",
		" | (_) || |_) || | | | |\\__ \\__ \\ | || (__ ",
		"  \\___/ | .__/ |_|_| |_||___/___/ |_| \\___|",
		"        | |                               ",
		"        |_|                               ",
	},
	"netbsd": {
		"\\\\\\`-______,----__",
		" \\\\        __,---`.",
		"  \\\\       `.____",
		"   \\\\            `---.",
		"    \\\\                `.",
		"     \\\\                 \\",
		"      \\\\                 \\",
		"       \\\\  ______         \\",
		"        \\\\ \\____ \\         \\",
		"         \\\\     \\ \\         \\",
		"          \\\\     \\ \\         \\",
		"           \\\\     \\ \\         \\",
		"            \\\\     \\ \\         \\",
		"             \\\\     \\ \\         \\",
	},
	"nixos": {
		"          \\\\  //       ",
		"         ==\\\\//==      ",
		"   \\\\      //          ",
		"    \\\\    //           ",
		"     \\\\  //     //     ",
		"======\\\\//=====//====== ",
		"      //\\\\    //       ",
		"     //  \\\\  //        ",
		"    //    \\\\//         ",
		"   //      \\\\          ",
		"         ==//\\\\==      ",
		"          //  \\\\       ",
	},
	"void": {
		"                __.;=====;.__",
		"            _.=+sync++==:..",
		"         .+#+==``       ``==+#+.",
		"       :++`                   `++:",
		"     .++`                       `++.",
		"    /+:                           :+/",
		"   /+:                             :+/",
		"  /+:                               :+/",
		" /+:                                 :+/",
		" /+:                                 :+/",
		" /+:                                 :+/",
		"  /+:                               :+/",
		"   /+:                             :+/",
		"    /+:                           :+/",
		"     .++`                       `++.",
		"       :++`                   `++:",
		"         .+#+==``       ``==+#+.",
		"            `~+sync++==:..`",
	},
	"pop": {
		"             /////////////                ",
		"         /////////////////////            ",
		"      ///////*              *///////      ",
		"    /////*                      */////    ",
		"   ////*                          *////   ",
		"  ////*                            *////  ",
		" /////     Pop!_OS System           ///// ",
		" /////                              ///// ",
		"  ////*                            *////  ",
		"   ////*                          *////   ",
		"    /////*                      */////    ",
		"      ///////*              *///////      ",
		"         /////////////////////            ",
		"             /////////////                ",
	},
}
